### ISSUE TITLE
Using only two decoder GRU?

### ISSUE THREAD

**Issue by ljun4121** [Kyubyong/tacotron#15]
Hi,
in network.py function decode1,

dec_ = attention_decoder(dec, hp.embed_size, memory, variable_scope="attention_decoder1") # (N, T', 256)
dec = dec_ + attention_decoder(dec_, hp.embed_size, memory, variable_scope="attention_decoder2") # (N, T', 256) # residual connections

In case of Tacotron, it uses attention RNN(1 layer GRU) and decoder RNN(2layer GRU). Attention in Tacotron scores memory(from encoder GRU) with query (from attention RNN) and makes context vector.
This context vector is concatenated with attention RNN's cell output to form decoder RNN's input.
Figure 1 in linked paper's architecture seems to be the same with Tacotron except that it has 8 layers.(https://arxiv.org/pdf/1609.08144.pdf)

Context vector should be shared for two decoder layers, but two attention decoder with different variable_scope will calculate context vector twice.

**Comment by Kyubyong** [comment]
Awesome! I've reflected your suggestion. One thing I think differently than you is I don't see the context vector should be shared for the folloing two layers because we are to do a residual connection vertically.

Sorry for my late response. Please check my revision, and leave any comments if necessary.
