### ISSUE TITLE
def load_vocab(): Is the vocab variable set properly?

### ISSUE THREAD

**Issue by basuam** [Kyubyong/tacotron#3]
@Kyubyong 
According to the comments, there should be a capital 'S' on the vocab variable, however, there is no 'S' but we have a " ' " (apostrophe).

> def load_vocab():
>     vocab = "E abcdefghijklmnopqrstuvwxyz'" # E: Empty, S: end of Sentence
>     char2idx = {char:idx for idx, char in enumerate(vocab)}
>     idx2char = {idx:char for idx, char in enumerate(vocab)}
>     return char2idx, idx2char 

If this is an error, does it affect the performance?
If it is not an error, can you clarify it? 

Thank you

**Comment by Kyubyong** [comment]
Sorry about the confusion. I didn't insert <EOS> unlike a typical  text training because we want to reconstruct silence. For example, if we want to synthesize a sentence "I love you", which takes 2 seconds, and the maximum duration is set to 10 seconds, then the last 8 seconds of the wav file should be silence.

**Comment by basuam** [comment]
@Kyubyong Thank you for your answer.
Then, the letter 'S' is not used on the progrma. If that's so, I can closed this "issue".
Please, let me know if my understanding is correct.
